# Generated by Django 3.2.10 on 2021-12-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='workinghours',
            field=models.CharField(default='10Am - 10PM', max_length=200),
        ),
    ]
