# Generated by Django 3.2.10 on 2021-12-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211222_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spice',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
