# Generated by Django 3.2.10 on 2022-04-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220414_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra', models.CharField(max_length=200)),
                ('events', models.CharField(max_length=200)),
                ('env', models.CharField(max_length=200)),
                ('achievements', models.CharField(max_length=200)),
                ('hostel', models.IntegerField()),
                ('naac', models.IntegerField()),
                ('NIRF', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('seats', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=1000)),
                ('special', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='placements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('package', models.IntegerField()),
                ('full_time', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='admissions',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.branch'),
        ),
    ]
